//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<double> Preco { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
    }
}
